export const EDIT_TODO = 'EDIT_TODO'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const SET_TODO = 'SET_TODO'
export const IMPORTANT_TODO = 'IMPORTANT_TODO'
export const CONFIRM_TODO = 'CONFIRM_TODO'
